In [1]:
import torch
torch.__version__

'2.8.0'

In [2]:
torch.cuda.is_available()

False

In [3]:
torch.accelerator.is_available()

True

In [4]:
torch.accelerator.current_accelerator()

device(type='mps')

In [6]:
torch.accelerator.current_accelerator().type

'mps'

In [6]:
device = torch.accelerator.current_accelerator().type \
         if torch.accelerator.is_available() \
         else torch.device("cpu")

print("Device: ", device)

Device:  mps


In [11]:
# Get GPU information
print(f"Device count:", torch.accelerator.device_count())
print(f"Device index:", torch.accelerator.current_device_index())

Device count: 1
Device index: 0


In [12]:
torch.mps.is_available()

True

In [2]:
print(f"Max recommended GPU memory: {torch.mps.recommended_max_memory():,} bytes")

Max recommended GPU memory: 17,179,885,568 bytes


In [3]:
torch.mps.current_allocated_memory()

0

In [4]:
torch.mps.driver_allocated_memory()

475136

In [15]:
x = torch.rand(5, 3)
x

tensor([[0.4879, 0.1235, 0.8564],
        [0.0838, 0.0443, 0.9228],
        [0.2166, 0.8752, 0.2758],
        [0.3280, 0.6379, 0.6951],
        [0.3745, 0.8950, 0.4805]])

In [18]:
y = x.to(device)
y

tensor([[0.4879, 0.1235, 0.8564],
        [0.0838, 0.0443, 0.9228],
        [0.2166, 0.8752, 0.2758],
        [0.3280, 0.6379, 0.6951],
        [0.3745, 0.8950, 0.4805]], device='mps:0')

In [19]:
x

tensor([[0.4879, 0.1235, 0.8564],
        [0.0838, 0.0443, 0.9228],
        [0.2166, 0.8752, 0.2758],
        [0.3280, 0.6379, 0.6951],
        [0.3745, 0.8950, 0.4805]])

In [20]:
y

tensor([[0.4879, 0.1235, 0.8564],
        [0.0838, 0.0443, 0.9228],
        [0.2166, 0.8752, 0.2758],
        [0.3280, 0.6379, 0.6951],
        [0.3745, 0.8950, 0.4805]], device='mps:0')

In [21]:
z = y.to("cpu")

In [22]:
z

tensor([[0.4879, 0.1235, 0.8564],
        [0.0838, 0.0443, 0.9228],
        [0.2166, 0.8752, 0.2758],
        [0.3280, 0.6379, 0.6951],
        [0.3745, 0.8950, 0.4805]])

In [ ]:
x[0][0] = 100

In [24]:
x

tensor([[1.0000e+02, 1.0000e+02, 1.0000e+02],
        [8.3838e-02, 4.4303e-02, 9.2279e-01],
        [2.1659e-01, 8.7522e-01, 2.7584e-01],
        [3.2798e-01, 6.3790e-01, 6.9513e-01],
        [3.7446e-01, 8.9501e-01, 4.8045e-01]])

In [28]:
y

tensor([[0.1230, 0.1235, 0.8564],
        [0.0838, 0.0443, 0.9228],
        [0.2166, 0.8752, 0.2758],
        [0.3280, 0.6379, 0.6951],
        [0.3745, 0.8950, 0.4805]], device='mps:0')

In [27]:
y[0, 0] = .123

In [29]:
z

tensor([[0.4879, 0.1235, 0.8564],
        [0.0838, 0.0443, 0.9228],
        [0.2166, 0.8752, 0.2758],
        [0.3280, 0.6379, 0.6951],
        [0.3745, 0.8950, 0.4805]])

In [30]:
import numpy as np

In [33]:
a = np.random.rand(5, 3)
a

array([[0.48959687, 0.90414549, 0.47842575],
       [0.21852651, 0.49512802, 0.27145411],
       [0.76367828, 0.2861526 , 0.02798613],
       [0.57723431, 0.30253119, 0.33724654],
       [0.87146748, 0.84062817, 0.38788825]])

In [35]:
x.to(device)

tensor([[1.0000e+02, 1.0000e+02, 1.0000e+02],
        [8.3838e-02, 4.4303e-02, 9.2279e-01],
        [2.1659e-01, 8.7522e-01, 2.7584e-01],
        [3.2798e-01, 6.3790e-01, 6.9513e-01],
        [3.7446e-01, 8.9501e-01, 4.8045e-01]], device='mps:0')

In [40]:
x.is_contiguous()

True

In [37]:
x1 = x.T
x1.is_contiguous()

False

In [38]:
x1.to(device)

tensor([[1.0000e+02, 8.3838e-02, 2.1659e-01, 3.2798e-01, 3.7446e-01],
        [1.0000e+02, 4.4303e-02, 8.7522e-01, 6.3790e-01, 8.9501e-01],
        [1.0000e+02, 9.2279e-01, 2.7584e-01, 6.9513e-01, 4.8045e-01]],
       device='mps:0')

In [45]:
# Scalars are 0-d tensors
s = torch.tensor(10)
print(s, s.ndim, s.shape)


tensor(10) 0 torch.Size([])


In [46]:
# Vectors are 1-d tensors

vector = torch.tensor([1, 2, 3])
print(vector, vector.ndim, vector.shape)


tensor([1, 2, 3]) 1 torch.Size([3])


In [47]:
# Matrices are 2-d tensors
matrix = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(matrix, matrix.ndim, matrix.shape)


tensor([[1, 2, 3],
        [4, 5, 6]]) 2 torch.Size([2, 3])


In [48]:
# Tensors are n-dimensional arrays
tensor = torch.tensor([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(tensor, tensor.ndim, tensor.shape)


tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]]) 3 torch.Size([2, 2, 2])


In [50]:
r = torch.rand(5, 5)
r

tensor([[0.2003, 0.6320, 0.3145, 0.7126, 0.1412],
        [0.7043, 0.9331, 0.2802, 0.6569, 0.6038],
        [0.0305, 0.2659, 0.9701, 0.6315, 0.0512],
        [0.2823, 0.7436, 0.8682, 0.1662, 0.0302],
        [0.3783, 0.0392, 0.2951, 0.8836, 0.9593]])

In [54]:
o = torch.ones(5, 5)
o

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [55]:
del o

In [56]:
a = torch.empty(5, 5)
a

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [65]:
print(a.shape, a.size())
print(a.dtype)
print(a.numel())
print(a.element_size())
print(a.device)
print(a.is_contiguous())
print(a.requires_grad)

torch.Size([5, 5]) torch.Size([5, 5])
torch.float32
25
4
cpu
True
False


In [ ]:
a.

In [70]:
a = torch.tensor(10)
print(a, id(a))
b = a.add(1)
print(a, b, id(a), id(b))
b = a.add_(1)  # In-place operation
print(a, b, id(a), id(b))

tensor(10) 5054053616
tensor(10) tensor(11) 5054053616 4976235120
tensor(11) tensor(11) 5054053616 5054053616


In [75]:
a = torch.arange(25).reshape(5, 5)
print(a, a.is_contiguous())

a.view(-1)

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]]) True


tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24])

In [77]:
b = a.T
print(b, b.is_contiguous())
b.view(-1)

tensor([[ 0,  5, 10, 15, 20],
        [ 1,  6, 11, 16, 21],
        [ 2,  7, 12, 17, 22],
        [ 3,  8, 13, 18, 23],
        [ 4,  9, 14, 19, 24]]) False


RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.

In [78]:
c = b.contiguous()
print(c, c.is_contiguous())
print(c.view(-1))

tensor([[ 0,  5, 10, 15, 20],
        [ 1,  6, 11, 16, 21],
        [ 2,  7, 12, 17, 22],
        [ 3,  8, 13, 18, 23],
        [ 4,  9, 14, 19, 24]]) True
tensor([ 0,  5, 10, 15, 20,  1,  6, 11, 16, 21,  2,  7, 12, 17, 22,  3,  8, 13,
        18, 23,  4,  9, 14, 19, 24])


In [87]:
a = torch.tensor([33, 12, 67, 89, 43, 12, 86, 18, 24, 27, 23, 15, 9, 78])
print(a)
print(a[0], a[1:5], a[-1])
print(a[[False, True, True, False, True, False, True, True, False, True, False, True, False, True]])
print(a[[2, 1, 0, 3, 8]])

print(a < 20)
print(a[a < 20])

tensor([33, 12, 67, 89, 43, 12, 86, 18, 24, 27, 23, 15,  9, 78])
tensor(33) tensor([12, 67, 89, 43]) tensor(78)
tensor([12, 67, 43, 86, 18, 27, 15, 78])
tensor([67, 12, 33, 89, 24])
tensor([False,  True, False, False, False,  True, False,  True, False, False,
        False,  True,  True, False])
tensor([12, 12, 18, 15,  9])


In [88]:
a = torch.arange(10)
a

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [91]:
n = list(range(10))
print(n)
#n + 5
print([x + 5 for x in n])

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[5, 6, 7, 8, 9, 10, 11, 12, 13, 14]


In [92]:
print(a)
a + 5

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


tensor([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [104]:
b = a.reshape(10, 1)
print(b, b.shape)

tensor([[0],
        [1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]]) torch.Size([10, 1])


In [105]:
a + b

tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
        [ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
        [ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13],
        [ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
        [ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
        [ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16],
        [ 8,  9, 10, 11, 12, 13, 14, 15, 16, 17],
        [ 9, 10, 11, 12, 13, 14, 15, 16, 17, 18]])

In [111]:
a = torch.arange(1_000_000)
a * 2

tensor([      0,       2,       4,  ..., 1999994, 1999996, 1999998])

In [112]:
%timeit a * 2

278 μs ± 1.77 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [113]:
b = a.to(device)
b

tensor([     0,      1,      2,  ..., 999997, 999998, 999999], device='mps:0')

In [114]:
%timeit b * 2

1.3 μs ± 41.2 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [115]:
1920 * 1080 * 3

6220800

In [116]:
del b

In [7]:
a = torch.arange(10, 20)
b = torch.arange(20, 30, device=device)
print(a, b)

tensor([10, 11, 12, 13, 14, 15, 16, 17, 18, 19]) tensor([20, 21, 22, 23, 24, 25, 26, 27, 28, 29], device='mps:0')


In [8]:
a + b

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, mps:0 and cpu!

In [9]:
a.to(device) + b

tensor([30, 32, 34, 36, 38, 40, 42, 44, 46, 48], device='mps:0')

In [19]:
import numpy as np
a = np.array([1, 2, 3])
print(a, type(a))

# Creates a new tensor - but shares the same underlying buffer of numpy
b = torch.from_numpy(a)  
print(b, type(b))

c = torch.tensor(a)
print(c, type(c))

a[0] = 10
print(a, b, c)

d = b.to(device)
a[0] += 5
print(a, b, c, d)


[1 2 3] <class 'numpy.ndarray'>
tensor([1, 2, 3]) <class 'torch.Tensor'>
tensor([1, 2, 3]) <class 'torch.Tensor'>
[10  2  3] tensor([10,  2,  3]) tensor([1, 2, 3])
[15  2  3] tensor([15,  2,  3]) tensor([1, 2, 3]) tensor([10,  2,  3], device='mps:0')


In [23]:
e = b.numpy()
print(b, e)
e[0] += 1
print(b, e)

tensor([15,  2,  3]) [15  2  3]
tensor([16,  2,  3]) [16  2  3]


In [24]:
t = torch.tensor([[1, 2, 3]])
print(t, t.shape, t.ndim)

tensor([[1, 2, 3]]) torch.Size([1, 3]) 2


In [26]:
t1 = t.squeeze()
print(t1, t1.shape, t1.ndim)

tensor([1, 2, 3]) torch.Size([3]) 1


In [ ]:
t2 = t1.(unsqueeze0)
print(t2, t2.shape)

t2 = t1.unsqueeze(1)
print(t2, t2.shape)


tensor([[1, 2, 3]]) torch.Size([1, 3])
tensor([[1],
        [2],
        [3]]) torch.Size([3, 1])


In [ ]:
a = np.array([1, 2, 3, 4])
print(a.reshape(-1, 1))
print(a.reshape(1, -1))


array([[1, 2, 3, 4]])

In [37]:
a = torch.tensor(10)
b = torch.tensor(20)
a + b
a.add_(b)

tensor(30)

In [38]:
a

tensor(30)

In [39]:
torch.add(a, b)

tensor(50)

In [41]:
a = torch.tensor([[[10, 20], [30, 40]], [[50, 60], [70, 80]]])
print(a, a.shape)

tensor([[[10, 20],
         [30, 40]],

        [[50, 60],
         [70, 80]]]) torch.Size([2, 2, 2])


In [45]:
b = a.flatten()
print(b, b.shape)
print(a, a.shape)

a[0, 1, 0] = 100
print(a, b, sep="\n")

tensor([ 10,  20, 100,  40,  50,  60,  70,  80]) torch.Size([8])
tensor([[[ 10,  20],
         [100,  40]],

        [[ 50,  60],
         [ 70,  80]]]) torch.Size([2, 2, 2])
tensor([[[ 10,  20],
         [100,  40]],

        [[ 50,  60],
         [ 70,  80]]])
tensor([ 10,  20, 100,  40,  50,  60,  70,  80])


In [59]:
x = torch.tensor(4, requires_grad=True, dtype=torch.float32)
print(x, x.requires_grad)

y = x ** 3
print(y, y.requires_grad)

z = y + 6
print(z, z.requires_grad)
print(x.grad)

z.backward()
print(x.grad)

tensor(4., requires_grad=True) True
tensor(64., grad_fn=<PowBackward0>) True
tensor(70., grad_fn=<AddBackward0>) True
None
tensor(48.)


In [60]:
# An example of gradient accumulation (not desired in this scenario)
weights = torch.ones(4, requires_grad=True)

for epoch in range(5):
    model_output = (weights * 3).sum()

    model_output.backward()
    print(f"{weights=}")
    print(f"{weights.grad=}")
    print("-" * 40)

weights=tensor([1., 1., 1., 1.], requires_grad=True)
weights.grad=tensor([3., 3., 3., 3.])
----------------------------------------
weights=tensor([1., 1., 1., 1.], requires_grad=True)
weights.grad=tensor([6., 6., 6., 6.])
----------------------------------------
weights=tensor([1., 1., 1., 1.], requires_grad=True)
weights.grad=tensor([9., 9., 9., 9.])
----------------------------------------
weights=tensor([1., 1., 1., 1.], requires_grad=True)
weights.grad=tensor([12., 12., 12., 12.])
----------------------------------------
weights=tensor([1., 1., 1., 1.], requires_grad=True)
weights.grad=tensor([15., 15., 15., 15.])
----------------------------------------


In [62]:
# An example of gradient accumulation (not desired in this scenario)
weights = torch.ones(4, requires_grad=True)

for epoch in range(5):
    model_output = (weights * 3).sum()

    model_output.backward()
    print(f"{weights=}")
    print(f"{weights.grad=}")
    print("-" * 40)
    weights.grad.zero_()  # Reset gradients after each epoch

weights=tensor([1., 1., 1., 1.], requires_grad=True)
weights.grad=tensor([3., 3., 3., 3.])
----------------------------------------
weights=tensor([1., 1., 1., 1.], requires_grad=True)
weights.grad=tensor([3., 3., 3., 3.])
----------------------------------------
weights=tensor([1., 1., 1., 1.], requires_grad=True)
weights.grad=tensor([3., 3., 3., 3.])
----------------------------------------
weights=tensor([1., 1., 1., 1.], requires_grad=True)
weights.grad=tensor([3., 3., 3., 3.])
----------------------------------------
weights=tensor([1., 1., 1., 1.], requires_grad=True)
weights.grad=tensor([3., 3., 3., 3.])
----------------------------------------


In [72]:
x = torch.tensor(4, requires_grad=True, dtype=torch.float32)
y = x ** 2

print(y, y.requires_grad)
print(x.grad)

tensor(16., grad_fn=<PowBackward0>) True
None


In [73]:
x = torch.tensor(4, requires_grad=True, dtype=torch.float32)
with torch.no_grad():
    y = x ** 2

print(y, y.requires_grad)
print(x.grad)

tensor(16.) False
None


In [79]:
x = torch.tensor(4, requires_grad=True, dtype=torch.float32)
y = x ** 2
z = x ** 3

print(y, y.requires_grad)
print(z, z.requires_grad)
print(x.grad)

y.backward()
print(x.grad)

z.backward()
print(x.grad)

tensor(16., grad_fn=<PowBackward0>) True
tensor(64., grad_fn=<PowBackward0>) True
None
tensor(8.)
tensor(56.)


In [81]:
x = torch.tensor(4, requires_grad=True, dtype=torch.float32)
y = x ** 2

with torch.no_grad():
    z = x ** 3

print(y, y.requires_grad)
print(z, z.requires_grad)
print(x.grad)

y.backward()
print(x.grad)

#z.backward()
print(x.grad)

tensor(16., grad_fn=<PowBackward0>) True
tensor(64.) False
None
tensor(8.)
tensor(8.)


In [83]:
y1 = y.detach()
print(y, y1)

tensor(16., grad_fn=<PowBackward0>) tensor(16.)


In [ ]:
a = torch.tensor(10)


False